name: Release

on:
    pull_request:
        branches: [main]
    workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install pnpm 9.8.0
              uses: pnpm/action-setup@v4.0.0
              with:
                  version: 9.8.0

            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            - name: Test turbo on CI
              run: pnpm turbo run -vvv --env-mode=loose --log-order=stream build --filter @rchat/shared
